package config_cmd

import L "glesha/logger"

const usageStr string = `
USAGE
glesha config [OPTIONS] <subcommand> [<args>]

DESCRIPTION
Manage glesha configuration. Get or set configuration values using JSONPath syntax.

SUBCOMMANDS
get         Get a configuration value
set         Set a configuration value
--interactive Interactive mode: prompt for each config value

OPTIONS
--file, -F <path>
    Path to config.json file
    Default: ~/.config/glesha/config.json

--log-level, -L <level>
    Set log level: debug info warn error panic
    Default: info

--color <mode>
    Set color mode: auto always never
    Default: auto

--interactive, -i
    Interactive mode: prompts for each config value
    Changes are applied after confirmation

GET USAGE
glesha config get [--file PATH] <path>

SET USAGE
glesha config set [--file PATH] <path> <value>

INTERACTIVE USAGE
glesha config --interactive [--file PATH]

PATHS (JSONPath syntax)
$.archive_format
$.provider
$.autogenerated
$.aws.access_key
$.aws.secret_key
$.aws.account_id
$.aws.region
$.aws.bucket_name
$.aws.storage_class

EXAMPLES
1. Get AWS region:
   glesha config get $.aws.region
   Output: aws.region: us-east-1

2. Set AWS access key:
   glesha config set $.aws.access_key AKIAIOSFODNN7EXAMPLE

3. Set account ID (auto-detected as uint64):
   glesha config set $.aws.account_id 123456789012

4. Get provider from custom config file:
   glesha config --file /path/to/custom.json get $.provider

5. Set boolean value:
   glesha config set $.autogenerated false

SEE ALSO
1. glesha help config (for config file structure details)
`

func Usage() string {
	return usageStr
}

func PrintUsage() {
	L.Print(usageStr)
}
