package add_cmd

import (
	"context"
	"errors"
	"fmt"
	"path/filepath"
	"time"

	"github.com/spf13/cobra"

	"glesha/config"
	"glesha/database"
	"glesha/database/repository"
	"glesha/file_io"
	L "glesha/logger"
)

type addCmdEnv struct {
	InputPath     string
	OutputPath    string
	ConfigPath    string
	WorkDir       string
	AssumeYes     bool
	Provider      config.Provider
	ArchiveFormat config.ArchiveFormat
}

var ErrNoExistingTask = errors.New("no existing task")

func NewAddCmd() *cobra.Command {
	var (
		outputPath    string
		configPath    string
		provider      string
		archiveFormat string
		assumeYes     bool
		workDir       string
	)

	cmd := &cobra.Command{
		Use:   "add PATH",
		Short: "Creates a glesha archive and upload task",
		Long:  Usage(),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) < 1 {
				return fmt.Errorf("PATH not provided. For more information check 'glesha help add'")
			}
			if len(args) > 1 {
				return fmt.Errorf("too many arguments. For more information check 'glesha help add'")
			}

			inputPath := args[0]

			var err error
			inputPath, err = file_io.ExpandTilde(inputPath)
			if err != nil {
				return fmt.Errorf("cannot expand ~ for inputPath: %w", err)
			}
			args[0] = inputPath

			if len(inputPath) == 0 {
				return fmt.Errorf("PATH is not valid")
			}

			readable, err := file_io.IsReadable(inputPath)
			if err != nil || !readable {
				return fmt.Errorf("input path is not readable: %s", inputPath)
			}

			workDir, err = file_io.GetGlobalWorkDir()
			if err != nil {
				return fmt.Errorf("could not get global work dir: %w", err)
			}

			if outputPath == "" {
				outputPath = workDir
			}

			outputPath, err = file_io.ExpandTilde(outputPath)
			if err != nil {
				return fmt.Errorf("cannot expand ~ for inputPath: %w", err)
			}

			if outputPath == "" {
				return fmt.Errorf("required arg outputPath is not provided")
			}

			if configPath == "" {
				defaultConfigPath, err := config.GetDefaultConfigPath()
				if err != nil {
					return fmt.Errorf("could not get default config path: %w", err)
				}
				configPath = defaultConfigPath
			}

			configPath, err = file_io.ExpandTilde(configPath)
			if err != nil {
				return fmt.Errorf("cannot expand ~ for inputPath: %w", err)
			}

			if configPath == "" {
				return fmt.Errorf("config path is empty")
			}
			readable, err = file_io.IsReadable(configPath)
			if err != nil || !readable {
				return fmt.Errorf("config is not readable: %s", configPath)
			}

			configPathAbs, err := filepath.Abs(configPath)
			if err != nil {
				return err
			}
			configPath = configPathAbs

			err = config.Parse(configPathAbs)
			if err != nil {
				return err
			}

			configs := config.Get()

			if configs.Autogenerated {
				L.Warn(config.GetAutoGenConfigWarning(configPathAbs))
			}

			if len(archiveFormat) > 0 {
				switch config.ArchiveFormat(archiveFormat) {
				case config.AF_TARGZ:
					L.Debug(fmt.Sprintf("Overriding archive format: %v -> %v", configs.ArchiveFormat, config.AF_TARGZ))
					configs.ArchiveFormat = config.AF_TARGZ
				default:
					return fmt.Errorf("invalid archive format: %s", archiveFormat)
				}
			}

			if len(provider) > 0 {
				parsedProvider, err := config.ParseProvider(provider)
				if err != nil {
					return err
				}
				L.Debug(fmt.Sprintf("Overriding provider: %v -> %v", configs.Provider, parsedProvider))
				configs.Provider = parsedProvider
			}

			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()

			inputPath := args[0]
			inputPathAbs, err := filepath.Abs(inputPath)
			if err != nil {
				return err
			}

			if inputPath == "" {
				return fmt.Errorf("required arg inputPath is not provided")
			}

			outputPathAbs, err := filepath.Abs(outputPath)
			if err != nil {
				return err
			}

			if outputPath == "" {
				return fmt.Errorf("output path is not available")
			}

			env := &addCmdEnv{
				InputPath:     inputPathAbs,
				OutputPath:    outputPathAbs,
				ConfigPath:    configPath,
				WorkDir:       workDir,
				AssumeYes:     assumeYes,
				ArchiveFormat: config.Get().ArchiveFormat,
				Provider:      config.Get().Provider,
			}

			dbPath, err := database.GetDBFilePath(ctx)
			if err != nil {
				return err
			}
			db, err := database.NewDB(dbPath)
			if err != nil {
				return err
			}
			err = db.Init(ctx)
			if err != nil {
				return err
			}
			defer db.Close(ctx)

			L.Info(fmt.Sprintf("Checking if files are changed in %s", env.InputPath))

			ignoredDirs := map[string]bool{
				filepath.Base(env.WorkDir): true,
			}
			filesInfo, err := file_io.ComputeFilesInfo(ctx, env.InputPath, ignoredDirs)
			if err != nil {
				return err
			}

			taskRepo := repository.NewTaskRepository(db)
			return queueTask(ctx, taskRepo, env, filesInfo)
		},
	}

	cmd.Flags().StringVarP(&outputPath, "output", "o", "",
		"Path to directory where archive should be generated")
	cmd.Flags().StringVarP(&configPath, "config", "c", "",
		"path to config.json to be used")
	cmd.Flags().StringVarP(&provider, "provider", "p", "",
		"Which provider to use for uploading")
	cmd.Flags().StringVarP(&archiveFormat, "archive-format", "a", "",
		"Which archive format to use for archiving")
	cmd.Flags().BoolVar(&assumeYes, "assume-yes", false,
		"Assume yes to all yes/no prompts")

	return cmd
}

func queueTask(ctx context.Context, taskRepo repository.TaskRepository, env *addCmdEnv, filesInfo *file_io.FilesInfo) error {
	task, err := taskRepo.FindSimilarTask(
		ctx,
		env.InputPath,
		env.Provider,
		filesInfo,
		env.ArchiveFormat,
	)
	if err != nil && err != database.ErrDoesNotExist {
		return err
	}
	var taskId int64
	if task != nil {
		taskId = task.Id
	}

	if err == database.ErrDoesNotExist {
		taskId, err = taskRepo.CreateTask(ctx,
			env.InputPath,
			env.OutputPath,
			env.ConfigPath,
			env.ArchiveFormat,
			env.Provider,
			time.Now(),
			time.Now(),
			filesInfo,
		)
		if err != nil {
			return err
		}
		L.Printf("Task created with id: %d\n", taskId)
	} else {
		L.Printf("Similar Task already exist with id: %d\n", taskId)
	}
	L.Printf("Use 'glesha run <id>' to run the task.\n")
	L.Printf("For more information, see 'glesha help add'.\n")
	return err
}
