package run_cmd

import (
	"context"
	"fmt"
	"strconv"
	"time"

	"github.com/spf13/cobra"

	"glesha/archive"
	"glesha/backend"
	"glesha/backend/aws"
	"glesha/config"
	"glesha/database"
	"glesha/database/model"
	"glesha/database/repository"
	"glesha/file_io"
	L "glesha/logger"
)

type RunCmdEnv struct {
	DB                *database.DB
	TaskId            int64
	Task              *model.Task
	TaskRepo          repository.TaskRepository
	UploadRepo        repository.UploadRepository
	UploadBlockRepo   repository.UploadBlockRepository
	FileCatalogRepo   repository.FileCatalogRepository
	MaxConcurrentJobs int
}

func NewRunCmd() *cobra.Command {
	var maxConcurrentJobs int

	cmd := &cobra.Command{
		Use:   "run ID",
		Short: "Runs a glesha task",
		Long:  Usage(),
		PreRunE: func(cmd *cobra.Command, args []string) error {
			if len(args) < 1 {
				return fmt.Errorf("no task Id provided. For more info check 'glesha help run'")
			}
			if len(args) > 1 {
				return fmt.Errorf("too many arguments. For more info, check 'glesha help run'")
			}
			return nil
		},
		RunE: func(cmd *cobra.Command, args []string) error {
			ctx := cmd.Context()

			taskId, err := strconv.ParseInt(args[0], 10, 64)
			if err != nil {
				return err
			}

			dbPath, err := database.GetDBFilePath(ctx)
			if err != nil {
				return err
			}
			db, err := database.NewDB(dbPath)
			if err != nil {
				return err
			}
			defer db.Close(ctx)
			L.Debug(fmt.Sprintf("Found database at: %s", dbPath))

			err = db.Init(ctx)
			if err != nil {
				return err
			}

			runCmdEnv := &RunCmdEnv{
				DB:                db,
				TaskId:            taskId,
				MaxConcurrentJobs: maxConcurrentJobs,
				TaskRepo:          repository.NewTaskRepository(db),
				UploadRepo:        repository.NewUploadRepository(db),
				UploadBlockRepo:   repository.NewUploadBlockRepository(db),
				FileCatalogRepo:   repository.NewFileCatalogRepository(db),
			}

			runCmdEnv.Task, err = runCmdEnv.TaskRepo.GetTaskById(ctx, runCmdEnv.TaskId)
			if err != nil {
				if err == database.ErrDoesNotExist {
					return fmt.Errorf("task %d does not exist, for more info see 'glesha help add'", runCmdEnv.TaskId)
				}
				return err
			}
			L.Printf("%s", runCmdEnv.Task)
			err = config.Parse(runCmdEnv.Task.ConfigPath)
			if err != nil {
				return err
			}

			if config.Get().Autogenerated {
				L.Warn(config.GetAutoGenConfigWarning(runCmdEnv.Task.ConfigPath))
			}
			return runTask(ctx, runCmdEnv)
		},
	}

	cmd.Flags().IntVarP(&maxConcurrentJobs, "jobs", "j", 1,
		"Set max workers to use for processing")

	return cmd
}

func runTask(ctx context.Context, runCmdEnv *RunCmdEnv) error {
	t := runCmdEnv.Task
	if t == nil {
		return fmt.Errorf("no task to run")
	}
	mustRearchive := false
	switch t.Status {
	case model.TASK_STATUS_QUEUED,
		model.TASK_STATUS_ARCHIVE_RUNNING,
		model.TASK_STATUS_ARCHIVE_ABORTED,
		model.TASK_STATUS_ARCHIVE_PAUSED:
		mustRearchive = true
	}

	var archiver archive.Archiver
	var err error
	switch t.ArchiveFormat {
	case config.AF_TARGZ:
		archiver, err = archive.NewTarGzArchiver(t)
		if err != nil {
			return err
		}
		archivePath := archiver.GetArchiveFilePath(ctx)
		L.Info("Planning archive")
		err = archiver.Plan(ctx)
		if err != nil {
			return err
		}
		L.Println("Plan Archive: OK")
		err = archive.IsValidTarGz(archivePath)
		if err != nil {
			mustRearchive = true
			L.Debug(err)
			L.Debug(fmt.Sprintf("Existing archive %s is not valid, starting fresh", archivePath))
		}
		info := archiver.GetInfo(ctx)
		if int64(info.SizeInBytes) != t.TotalSize {
			L.Info("Rearchiving because input_path contents have changed since last run")
			mustRearchive = true
		}
	default:
		return fmt.Errorf("archive format %s is not supported yet", t.ArchiveFormat.String())
	}

	if mustRearchive {
		L.Info("Starting fresh because cannot continue from previous state")
		err = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_ARCHIVE_RUNNING)
		if err != nil {
			return err
		}
		err = archiver.Start(ctx, runCmdEnv.FileCatalogRepo, runCmdEnv.TaskRepo)
		if err != nil {
			_ = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_ARCHIVE_ABORTED)
			return err
		}
		select {
		case <-ctx.Done():
			_ = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_ARCHIVE_ABORTED)
			return fmt.Errorf("kill signal received, exiting")
		default:
		}
		err = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_ARCHIVE_COMPLETED)
		if err != nil {
			return err
		}
		err = runCmdEnv.TaskRepo.UpdateTaskContentInfo(ctx,
			runCmdEnv.TaskId, archiver.GetInfo(ctx))
		if err != nil {
			return err
		}
		L.Println("Create Archive: OK")
	} else {
		L.Info("Skipping Archiving because input_path contents have not changed since last run")
	}

	archivePath := archiver.GetArchiveFilePath(ctx)
	L.Printf("Archive: %s\n", archivePath)

	if runCmdEnv.Task.Provider != config.PROVIDER_AWS {
		return fmt.Errorf("unsupported provider: %v", runCmdEnv.Task.Provider.String())
	}

	var storageBackendFactory backend.StorageFactory = &aws.AWSFactory{}
	storageBackend, err := storageBackendFactory.NewStorageBackend()
	if err != nil {
		return err
	}

	err = storageBackend.CreateResourceContainer(ctx)
	if err != nil {
		return err
	}
	L.Println("Upload::CreateResourceContainer OK")

	existingUpload, err := runCmdEnv.UploadRepo.GetUploadByTaskId(ctx, runCmdEnv.TaskId)

	var uploadId int64

	if err != nil && err == database.ErrDoesNotExist {
		uploadRes, err2 := storageBackend.CreateUploadResource(ctx,
			runCmdEnv.Task.Key(), archivePath)
		if err2 != nil {
			return err2
		}
		L.Println("Upload::CreateUploadResource OK")
		archiveFileInfo, err2 := file_io.GetFileInfo(archivePath)
		if err2 != nil {
			return err2
		}

		blockSizeInBytes := uploadRes.BlockSizeInBytes
		archiveFileSize := int64(archiveFileInfo.Size)
		var totalBlocks int64 = 1
		if blockSizeInBytes > 0 {
			totalBlocks = (archiveFileSize + blockSizeInBytes - 1) / blockSizeInBytes
		}

		err2 = storageBackend.IsBlockSizeOK(blockSizeInBytes, archiveFileSize)
		if err2 != nil {
			return fmt.Errorf("failed to partition file: %w", err)
		}
		now := time.Now()
		uploadId, err2 = runCmdEnv.UploadRepo.CreateUpload(
			ctx,
			runCmdEnv.TaskId,
			uploadRes.Metadata.Json,
			uploadRes.Metadata.SchemaVersion,
			archivePath,
			int64(archiveFileInfo.Size),
			archiveFileInfo.ModifiedAt,
			totalBlocks,
			blockSizeInBytes,
			now,
			now,
		)

		if err2 != nil {
			return fmt.Errorf("failed to save upload information: %w", err)
		}
		L.Printf("Upload::CreateUploadResource OK (upload_id: %d)\n", uploadId)
		err = nil
	} else if err != nil {
		return fmt.Errorf("could not get upload for task id %d: %w", runCmdEnv.TaskId, err)
	} else {
		L.Info("Skipping creating a new upload because upload already exists for a task")
		uploadId = existingUpload.Id
	}
	L.Println(fmt.Sprintf("Task(%d) now has upload Id: %d", runCmdEnv.TaskId, uploadId))
	if err != nil {
		return err
	}

	_ = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_UPLOAD_RUNNING)
	_ = runCmdEnv.UploadRepo.UpdateStatus(ctx, uploadId, model.UPLOAD_STATUS_RUNNING)

	err = storageBackend.UploadResource(
		ctx,
		runCmdEnv.TaskRepo,
		runCmdEnv.UploadRepo,
		runCmdEnv.UploadBlockRepo,
		runCmdEnv.MaxConcurrentJobs,
		uploadId,
	)

	if err != nil {
		_ = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_UPLOAD_ABORTED)
		_ = runCmdEnv.UploadRepo.UpdateStatus(ctx, uploadId, model.UPLOAD_STATUS_FAILED)
		return err
	}
	_ = runCmdEnv.TaskRepo.UpdateTaskStatus(ctx, runCmdEnv.TaskId, model.TASK_STATUS_UPLOAD_COMPLETED)
	L.Printf("Upload Archive: OK\n")
	return nil
}
