package config

import (
	"fmt"
	"reflect"
	"slices"
	"strconv"
	"strings"
)

func ParsePath(path string) ([]string, error) {
	if !strings.HasPrefix(path, "$") {
		return nil, fmt.Errorf("path must start with $")
	}
	path = path[1:]
	if len(path) == 0 {
		return nil, fmt.Errorf("path is empty")
	}
	path = strings.TrimPrefix(path, ".")
	segments := strings.Split(path, ".")
	if slices.Contains(segments, "") {
		return nil, fmt.Errorf("invalid path: empty segment")
	}
	return segments, nil
}

func GetValueByPath(cfg *Config, path string) (any, error) {
	segments, err := ParsePath(path)
	if err != nil {
		return nil, err
	}

	if len(segments) == 1 {
		switch segments[0] {
		case "archive_format":
			return cfg.ArchiveFormat, nil
		case "provider":
			return cfg.Provider, nil
		case "autogenerated":
			return cfg.Autogenerated, nil
		}
		return nil, fmt.Errorf("unknown config key: %s", segments[0])
	}

	if segments[0] == "aws" && len(segments) == 2 {
		if cfg.Aws == nil {
			return nil, fmt.Errorf("aws config is nil")
		}
		switch segments[1] {
		case "access_key":
			return cfg.Aws.AccessKey, nil
		case "secret_key":
			return cfg.Aws.SecretKey, nil
		case "account_id":
			return cfg.Aws.AccountId, nil
		case "region":
			return cfg.Aws.Region, nil
		case "bucket_name":
			return cfg.Aws.BucketName, nil
		case "storage_class":
			return cfg.Aws.StorageClass, nil
		}
		return nil, fmt.Errorf("unknown aws config key: %s", segments[1])
	}

	return nil, fmt.Errorf("invalid path: %s", path)
}

func SetValueByPath(cfg *Config, path string, value string) error {
	segments, err := ParsePath(path)
	if err != nil {
		return err
	}

	var fieldType reflect.Type
	var target any

	if len(segments) == 1 {
		switch segments[0] {
		case "archive_format":
			fieldType = reflect.TypeOf(ArchiveFormat(""))
			target = &cfg.ArchiveFormat
		case "provider":
			fieldType = reflect.TypeOf(Provider(""))
			target = &cfg.Provider
		case "autogenerated":
			fieldType = reflect.TypeOf(false)
			target = &cfg.Autogenerated
		default:
			return fmt.Errorf("unknown config key: %s", segments[0])
		}
	} else if segments[0] == "aws" && len(segments) == 2 {
		if cfg.Aws == nil {
			cfg.Aws = &Aws{}
		}
		switch segments[1] {
		case "access_key":
			fieldType = reflect.TypeOf("")
			target = &cfg.Aws.AccessKey
		case "secret_key":
			fieldType = reflect.TypeOf("")
			target = &cfg.Aws.SecretKey
		case "account_id":
			fieldType = reflect.TypeOf(uint64(0))
			target = &cfg.Aws.AccountId
		case "region":
			fieldType = reflect.TypeOf("")
			target = &cfg.Aws.Region
		case "bucket_name":
			fieldType = reflect.TypeOf("")
			target = &cfg.Aws.BucketName
		case "storage_class":
			fieldType = reflect.TypeOf("")
			target = &cfg.Aws.StorageClass
		default:
			return fmt.Errorf("unknown aws config key: %s", segments[1])
		}
	} else {
		return fmt.Errorf("invalid path: %s", path)
	}

	val, err := parseValue(value, fieldType)
	if err != nil {
		return err
	}

	reflect.ValueOf(target).Elem().Set(reflect.ValueOf(val))
	return nil
}

func parseValue(value string, fieldType reflect.Type) (any, error) {
	if fieldType == reflect.TypeOf(ArchiveFormat("")) {
		return ParseArchiveFormat(value)
	}
	if fieldType == reflect.TypeOf(Provider("")) {
		return ParseProvider(value)
	}

	if fieldType.Kind() == reflect.Bool {
		switch strings.ToLower(value) {
		case "true":
			return true, nil
		case "false":
			return false, nil
		}
		return nil, fmt.Errorf("invalid boolean value: %s", value)
	}

	if fieldType.Kind() == reflect.Uint64 {
		val, err := strconv.ParseUint(value, 10, 64)
		if err == nil {
			return val, nil
		}
		return nil, fmt.Errorf("invalid uint64 value: %s", value)
	}

	if fieldType.Kind() == reflect.Int {
		val, err := strconv.Atoi(value)
		if err == nil {
			return val, nil
		}
		return nil, fmt.Errorf("invalid int value: %s", value)
	}

	return value, nil
}
