package config

import (
	"fmt"
	"strconv"
	"strings"
)

func ParsePath(path string) ([]string, error) {
	if !strings.HasPrefix(path, "$") {
		return nil, fmt.Errorf("path must start with $")
	}
	path = path[1:]
	if len(path) == 0 {
		return nil, fmt.Errorf("path is empty")
	}
	path = strings.TrimPrefix(path, ".")
	segments := strings.Split(path, ".")
	for _, s := range segments {
		if s == "" {
			return nil, fmt.Errorf("invalid path: empty segment")
		}
	}
	return segments, nil
}

func GetValueByPath(cfg *Config, path string) (any, error) {
	segments, err := ParsePath(path)
	if err != nil {
		return nil, err
	}

	if len(segments) == 1 {
		switch segments[0] {
		case "archive_format":
			return cfg.ArchiveFormat, nil
		case "provider":
			return cfg.Provider, nil
		case "autogenerated":
			return cfg.Autogenerated, nil
		}
		return nil, fmt.Errorf("unknown config key: %s", segments[0])
	}

	if segments[0] == "aws" && len(segments) == 2 {
		if cfg.Aws == nil {
			return nil, fmt.Errorf("aws config is nil")
		}
		switch segments[1] {
		case "access_key":
			return cfg.Aws.AccessKey, nil
		case "secret_key":
			return cfg.Aws.SecretKey, nil
		case "account_id":
			return cfg.Aws.AccountId, nil
		case "region":
			return cfg.Aws.Region, nil
		case "bucket_name":
			return cfg.Aws.BucketName, nil
		case "storage_class":
			return cfg.Aws.StorageClass, nil
		}
		return nil, fmt.Errorf("unknown aws config key: %s", segments[1])
	}

	return nil, fmt.Errorf("invalid path: %s", path)
}

func SetValueByPath(cfg *Config, path string, value string) error {
	segments, err := ParsePath(path)
	if err != nil {
		return err
	}

	if len(segments) == 1 {
		switch segments[0] {
		case "archive_format":
			v, err := ParseArchiveFormat(value)
			if err != nil {
				return err
			}
			cfg.ArchiveFormat = v
			return nil
		case "provider":
			v, err := ParseProvider(value)
			if err != nil {
				return err
			}
			cfg.Provider = v
			return nil
		case "autogenerated":
			v, err := parseBool(value)
			if err != nil {
				return err
			}
			cfg.Autogenerated = v
			return nil
		default:
			return fmt.Errorf("unknown config key: %s", segments[0])
		}
	}

	if segments[0] == "aws" && len(segments) == 2 {
		if cfg.Aws == nil {
			cfg.Aws = &Aws{}
		}
		switch segments[1] {
		case "access_key":
			cfg.Aws.AccessKey = value
		case "secret_key":
			cfg.Aws.SecretKey = value
		case "account_id":
			v, err := parseUint64(value)
			if err != nil {
				return err
			}
			cfg.Aws.AccountId = v
		case "region":
			cfg.Aws.Region = value
		case "bucket_name":
			cfg.Aws.BucketName = value
		case "storage_class":
			cfg.Aws.StorageClass = value
		default:
			return fmt.Errorf("unknown aws config key: %s", segments[1])
		}
		return nil
	}

	return fmt.Errorf("invalid path: %s", path)
}

func parseBool(value string) (bool, error) {
	switch strings.ToLower(value) {
	case "true":
		return true, nil
	case "false":
		return false, nil
	}
	return false, fmt.Errorf("invalid boolean value: %s", value)
}

func parseUint64(value string) (uint64, error) {
	v, err := strconv.ParseUint(value, 10, 64)
	if err != nil {
		return 0, fmt.Errorf("invalid uint64 value: %s", value)
	}
	return v, nil
}
